package main

func printHelp() {
	println("vx - A modern vi text editor")
	println("")
	println("USAGE:")
	println("  vx [filename]         Open file for editing")
	println("  vx -h, --help         Show this help message")
	println("  vx -v, --version      Show version information")
	println("")
	println("NORMAL MODE COMMANDS:")
	println("  h/j/k/l              Move cursor left/down/up/right")
	println("  i                    Enter insert mode")
	println("  :                    Enter command mode")
	println("  /                    Search")
	println("  n/N                  Next/previous search result")
	println("  c                    Copy current line")
	println("  p                    Paste (or toggle preview for .md files)")
	println("  u                    Undo")
	println("  r                    Redo")
	println("  gg                   Jump to start of file")
	println("  G                    Jump to end of file")
	println("  q                    Quit")
	println("  Ctrl+C               Force quit")
	println("")
	println("COMMAND MODE:")
	println("  :w                   Save file")
	println("  :w filename          Save as filename")
	println("  :q                   Quit")
	println("  :q!                  Force quit without saving")
	println("  :wq                  Save and quit")
	println("  :e filename          Edit new file")
	println("")
	println("MARKDOWN PREVIEW:")
	println("  p                    Toggle preview (in .md files)")
	println("  j/k or arrows        Scroll preview")
	println("")
	println("For more information, visit: https://github.com/Adelodunpeter25/vx")
}
