package main

func printHelp() {
	println("vx - A modern vi text editor")
	println("")
	println("USAGE:")
	println("  vx [filename]         Open file for editing")
	println("  vx -h, --help         Show this help message")
	println("  vx -v, --version      Show version information")
	println("")
	println("FEATURES:")
	println("  Modal editing         Normal, insert, command, search, replace")
	println("  Split panes           Edit multiple files side by side")
	println("  File browser          Toggleable sidebar with preview/open")
	println("  Palette               Ctrl+P fuzzy file picker")
	println("  Markdown preview      Full-screen preview for .md files")
	println("  Syntax highlighting   Chroma-based highlighting")
	println("  Undo/redo             Full edit history")
	println("")
	println("NORMAL MODE NAVIGATION:")
	println("  h/j/k/l              Move cursor left/down/up/right")
	println("  w/b                  Move forward/backward by word")
	println("  gg / G               Jump to start / end of file")
	println("  Ctrl+U / Ctrl+D      Page up / page down")
	println("")
	println("NORMAL MODE EDITING:")
	println("  i                    Enter insert mode")
	println("  x / Ctrl+X           Cut (selection or character)")
	println("  dd                   Delete current line")
	println("  u / Ctrl+Z           Undo")
	println("  r / Ctrl+Y           Redo")
	println("  Ctrl+C               Copy (selection or current line)")
	println("  Ctrl+V               Paste")
	println("  p                    Paste (or toggle preview for .md)")
	println("  / or Ctrl+F          Search (incremental)")
	println("  Shift+H              Find and replace")
	println("  n / N                Next / prev search result")
	println("  Ctrl+A               Select all")
	println("  Ctrl+P               Open file palette")
	println("")
	println("FILE & PANE MANAGEMENT:")
	println("  Ctrl+S               Save")
	println("  Ctrl+O               Open file")
	println("  Ctrl+W               Close pane")
	println("  Ctrl+N               Next pane")
	println("  Ctrl+B               Toggle file browser")
	println("  q / Ctrl+Q           Quit")
	println("  Esc                  Clear selection")
	println("  :                    Enter command mode")
	println("")
	println("INSERT MODE:")
	println("  Esc                  Return to normal mode")
	println("  Ctrl+S               Save")
	println("  Ctrl+Z               Undo")
	println("  Ctrl+Y               Redo")
	println("")
	println("MOUSE SELECTION:")
	println("  Click & drag         Select text (auto-scrolls)")
	println("  Ctrl+C               Copy")
	println("  Ctrl+X               Cut")
	println("")
	println("COMMAND MODE:")
	println("  :w [name]            Save (as)")
	println("  :q / :q!             Quit / force quit")
	println("  :wq                  Save and quit")
	println("  :e name              Open file in pane")
	println("  :b name              Open file in new pane")
	println("  :db                  Close pane")
	println("  :f                   Toggle file browser")
	println("  :cd [path]           Change directory")
	println("  :set:show/hide-hidden")
	println("")
	println("MARKDOWN PREVIEW:")
	println("  p                    Toggle preview")
	println("  j/k arrows gg G      Scroll")
	println("  Ctrl+U / Ctrl+D      Page up / down")
	println("")
	println("For more info: https://github.com/Adelodunpeter25/vx")
}
