package main

func printHelp() {
	println("vx - A modern vi text editor")
	println("")
	println("USAGE:")
	println("  vx [filename]         Open file for editing")
	println("  vx -h, --help         Show this help message")
	println("  vx -v, --version      Show version information")
	println("")
	println("NORMAL MODE COMMANDS:")
	println("  h/j/k/l              Move cursor left/down/up/right")
	println("  w/b                  Move forward/backward by word")
	println("  i                    Enter insert mode")
	println("  :                    Enter command mode")
	println("  / or Ctrl+F          Search (real-time incremental)")
	println("  Shift+H              Find and replace")
	println("  n/N                  Next/previous search result")
	println("  c                    Copy current line (or selection)")
	println("  x                    Cut selection (or delete character)")
	println("  p                    Paste (or toggle preview for .md files)")
	println("  dd                   Delete current line")
	println("  u                    Undo")
	println("  r                    Redo")
	println("  gg                   Jump to start of file")
	println("  G                    Jump to end of file")
	println("  Ctrl+S               Save file")
	println("  Ctrl+N/P             Next/previous pane")
	println("  Esc                  Clear selection")
	println("  q                    Quit")
	println("  Ctrl+C               Force quit")
	println("")
	println("MOUSE SELECTION:")
	println("  Click and drag       Select text (auto-scrolls at edges)")
	println("  c                    Copy selected text")
	println("  x                    Cut selected text")
	println("  Esc or movement      Clear selection")
	println("")
	println("COMMAND MODE:")
	println("  :w                   Save file")
	println("  :w filename          Save as filename")
	println("  :q                   Quit")
	println("  :q!                  Force quit without saving")
	println("  :wq                  Save and quit")
	println("  :e filename          Edit new file (replace current pane)")
	println("  :b filename          Open file in new pane")
	println("  :db                  Close current pane")
	println("  :f                   Toggle file browser sidebar")
	println("")
	println("MARKDOWN PREVIEW:")
	println("  p                    Toggle preview (in .md files)")
	println("  j/k or arrows        Scroll preview")
	println("")
	println("FILE BROWSER:")
	println("  :f                   Toggle file browser sidebar")
	println("")
	println("For more information, visit: https://github.com/Adelodunpeter25/vx")
}
